2024-11-14 13:43:40,248 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 13:43:40,249 - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-11-14 13:43:40,251 - INFO - Console is ready and is listening for commands

2024-11-14 13:43:40,251 - INFO - logging in using static token
2024-11-14 13:43:40,746 - INFO - Shard ID None has connected to Gateway (Session ID: 2c716a9cb5812aea7f61bf0912363f09).
2024-11-14 13:43:42,752 - INFO - Bot ready.
2024-11-14 13:43:44,829 - INFO - NEW OBJECT ON global_variables/openedRentals.json: DATA {1306615557000269854: {'renter_id': 787065576995553301, 'is_active': None, 'employee_id': None, 'guild_id': 1274894955663593492}}
2024-11-14 13:43:48,766 - INFO - OBJECT DELETED ON global_variables/openedRentals.json: KEY 1306615557000269854; DATA: {'renter_id': 787065576995553301, 'is_active': None, 'employee_id': None, 'guild_id': 1274894955663593492}
2024-11-14 14:00:12,677 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 14:00:12,677 - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-11-14 14:00:12,679 - INFO - Console is ready and is listening for commands

2024-11-14 14:00:12,679 - INFO - logging in using static token
2024-11-14 14:00:13,195 - INFO - Shard ID None has connected to Gateway (Session ID: 5697e091435c396d27f461b07b51e28a).
2024-11-14 14:00:15,238 - INFO - Bot ready.
2024-11-14 14:00:18,326 - INFO - NEW OBJECT ON global_variables/openedRentals.json: DATA {1306619723332583496: {'renter_id': 787065576995553301, 'is_active': None, 'employee_id': None, 'guild_id': 1274894955663593492}}
2024-11-14 14:00:22,052 - INFO - 1306619723332583496 closing in 1 minute.
2024-11-14 14:01:22,279 - ERROR - Ignoring exception in command 'scheduleclosing'
Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/discord/app_commands/commands.py", line 858, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/ovr-bot/src/bot.py", line 197, in scheduleclosing
    transcript=transcript(ctx)
               ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'transcript' where it is not associated with a value

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/discord/app_commands/tree.py", line 1310, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/discord/app_commands/commands.py", line 883, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/discord/app_commands/commands.py", line 876, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'scheduleclosing' raised an exception: UnboundLocalError: cannot access local variable 'transcript' where it is not associated with a value
2024-11-14 14:03:11,944 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 14:03:11,945 - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-11-14 14:03:11,947 - INFO - Console is ready and is listening for commands

2024-11-14 14:03:11,947 - INFO - logging in using static token
2024-11-14 14:03:12,805 - INFO - Shard ID None has connected to Gateway (Session ID: bfb369b62e05dfc66c74ea5d10173d05).
2024-11-14 14:03:14,816 - INFO - Bot ready.
2024-11-14 14:03:17,252 - INFO - 1306619723332583496 closing in 1 minute.
2024-11-14 14:04:17,606 - INFO - OBJECT DELETED ON global_variables/openedRentals.json: KEY 1306619723332583496; DATA: {'renter_id': 787065576995553301, 'is_active': None, 'employee_id': None, 'guild_id': 1274894955663593492}
2024-11-14 14:05:26,502 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 14:05:26,503 - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-11-14 14:05:26,505 - INFO - Console is ready and is listening for commands

2024-11-14 14:05:26,505 - INFO - logging in using static token
2024-11-14 14:05:26,952 - INFO - Shard ID None has connected to Gateway (Session ID: 69efb272b528cd176b94f5132f1ecfa6).
2024-11-14 14:05:29,001 - INFO - Bot ready.
2024-11-14 14:05:32,065 - INFO - NEW OBJECT ON global_variables/openedRentals.json: DATA {1306621040381661288: {'renter_id': 787065576995553301, 'is_active': None, 'employee_id': None, 'guild_id': 1274894955663593492}}
2024-11-14 14:05:35,464 - INFO - 1306621040381661288 closing in 1 minute.
2024-11-14 14:06:35,957 - INFO - OBJECT DELETED ON global_variables/openedRentals.json: KEY 1306621040381661288; DATA: {'renter_id': 787065576995553301, 'is_active': None, 'employee_id': None, 'guild_id': 1274894955663593492}
2024-11-14 14:08:20,786 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 14:08:20,787 - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-11-14 14:08:20,789 - INFO - Console is ready and is listening for commands

2024-11-14 14:08:20,789 - INFO - logging in using static token
2024-11-14 14:08:21,270 - INFO - Shard ID None has connected to Gateway (Session ID: 16da5a5c943e42b986a1ceaf8d1f253a).
2024-11-14 14:08:23,279 - INFO - Bot ready.
2024-11-14 14:08:25,247 - INFO - NEW OBJECT ON global_variables/openedRentals.json: DATA {1306621765258313840: {'renter_id': 787065576995553301, 'is_active': None, 'employee_id': None, 'guild_id': 1274894955663593492}}
2024-11-14 14:08:31,173 - INFO - 1306621765258313840 closing in 1 minute.
2024-11-14 14:09:31,522 - INFO - OBJECT DELETED ON global_variables/openedRentals.json: KEY 1306621765258313840; DATA: {'renter_id': 787065576995553301, 'is_active': None, 'employee_id': None, 'guild_id': 1274894955663593492}
2024-11-14 14:10:37,027 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 14:10:37,028 - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-11-14 14:10:37,029 - INFO - Console is ready and is listening for commands

2024-11-14 14:10:37,030 - INFO - logging in using static token
2024-11-14 14:10:37,649 - INFO - Shard ID None has connected to Gateway (Session ID: 38ec7a312d0b3fd0a2bf16b653925335).
2024-11-14 14:10:39,655 - ERROR - Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/workspaces/ovr-bot/src/bot.py", line 61, in on_ready
    v.add_item(buttons.ticket_general())
               ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'static.buttons' has no attribute 'ticket_general' (most likely due to a circular import)
2024-11-14 14:14:16,672 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 14:14:16,674 - INFO - Console is ready and is listening for commands

2024-11-14 14:14:16,674 - INFO - logging in using static token
2024-11-14 14:14:17,287 - INFO - Shard ID None has connected to Gateway (Session ID: 9f309feb1c1ba37283f7aeca913b1197).
2024-11-14 14:14:20,532 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 14:14:20,533 - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-11-14 14:14:20,534 - INFO - Console is ready and is listening for commands

2024-11-14 14:14:20,535 - INFO - logging in using static token
2024-11-14 14:14:21,051 - INFO - Shard ID None has connected to Gateway (Session ID: 40370aa4b92c19fc921bfadff162afc0).
2024-11-14 14:14:23,063 - ERROR - Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/workspaces/ovr-bot/src/bot.py", line 61, in on_ready
    v.add_item(buttons.ticket_general())
               ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'static.buttons' has no attribute 'ticket_general' (most likely due to a circular import)
2024-11-14 14:14:42,097 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 14:14:42,099 - INFO - Console is ready and is listening for commands

2024-11-14 14:14:42,099 - INFO - logging in using static token
2024-11-14 14:14:42,739 - INFO - Shard ID None has connected to Gateway (Session ID: 7a3f8917dcbd282a230bd62506571a20).
2024-11-14 14:14:44,727 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 14:14:44,728 - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-11-14 14:14:44,729 - INFO - Console is ready and is listening for commands

2024-11-14 14:14:44,730 - INFO - logging in using static token
2024-11-14 14:14:45,158 - INFO - Shard ID None has connected to Gateway (Session ID: 9fa375ae305568efd5aaf69dfec4a665).
2024-11-14 14:14:47,171 - ERROR - Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/workspaces/ovr-bot/src/bot.py", line 61, in on_ready
    v.add_item(buttons.ticket_general())
               ^^^^^^^
NameError: name 'buttons' is not defined
2024-11-14 14:16:19,773 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 14:16:19,775 - INFO - Console is ready and is listening for commands

2024-11-14 14:16:19,775 - INFO - logging in using static token
2024-11-14 14:16:20,333 - INFO - Shard ID None has connected to Gateway (Session ID: 40cdb5653bf4147ba254106f2ccb1eb6).
2024-11-14 14:16:22,541 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 14:16:22,542 - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-11-14 14:16:22,544 - INFO - Console is ready and is listening for commands

2024-11-14 14:16:22,544 - INFO - logging in using static token
2024-11-14 14:16:23,006 - INFO - Shard ID None has connected to Gateway (Session ID: b26eae3a6c432f5a828655af55192f49).
2024-11-14 14:16:25,016 - ERROR - Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/workspaces/ovr-bot/src/bot.py", line 61, in on_ready
    buttonss=imports.buttons()
             ^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'imports' has no attribute 'buttons' (most likely due to a circular import)
2024-11-14 14:18:17,520 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 14:18:17,522 - INFO - Console is ready and is listening for commands

2024-11-14 14:18:17,522 - INFO - logging in using static token
2024-11-14 14:18:17,991 - INFO - Shard ID None has connected to Gateway (Session ID: 2cc26b33b108a0cc6ea4816624cc804b).
2024-11-14 14:18:21,801 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 14:18:21,802 - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-11-14 14:18:21,803 - INFO - Console is ready and is listening for commands

2024-11-14 14:18:21,804 - INFO - logging in using static token
2024-11-14 14:18:22,211 - INFO - Shard ID None has connected to Gateway (Session ID: c07c7080dfd41439e1f7d913ee6b8203).
2024-11-14 14:18:24,219 - ERROR - Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/workspaces/ovr-bot/src/bot.py", line 61, in on_ready
    buttonss=imports.buttons()
             ^^^^^^^^^^^^^^^^^
  File "/workspaces/ovr-bot/src/imports.py", line 4, in buttons
    return buttons.rental_close(), buttons.ticket_close(), buttons.ticket_general(), buttons.ticket_management()
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'rental_close'
2024-11-14 14:20:17,669 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 14:20:17,670 - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-11-14 14:20:17,671 - INFO - Console is ready and is listening for commands

2024-11-14 14:20:17,672 - INFO - logging in using static token
2024-11-14 14:20:18,213 - INFO - Shard ID None has connected to Gateway (Session ID: 84a609279ef9813f81fc0ad11f379786).
2024-11-14 14:20:20,258 - INFO - Bot ready.
2024-11-14 14:20:33,343 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 14:20:33,343 - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-11-14 14:20:33,345 - INFO - Console is ready and is listening for commands

2024-11-14 14:20:33,345 - INFO - logging in using static token
2024-11-14 14:20:33,852 - INFO - Shard ID None has connected to Gateway (Session ID: f535ba27c19a73f6febb9a28c1371470).
2024-11-14 14:20:35,877 - ERROR - Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/workspaces/ovr-bot/src/bot.py", line 61, in on_ready
    buttonss=imports.buttonss()
             ^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'imports' has no attribute 'buttonss' (most likely due to a circular import)
2024-11-14 14:23:17,644 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 14:23:17,646 - INFO - Console is ready and is listening for commands

2024-11-14 14:23:17,646 - INFO - logging in using static token
2024-11-14 14:23:18,126 - INFO - Shard ID None has connected to Gateway (Session ID: 96d43465d58dd85003aa07de60c0dd57).
2024-11-14 14:23:19,827 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 14:23:19,828 - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-11-14 14:23:19,829 - INFO - Console is ready and is listening for commands

2024-11-14 14:23:19,830 - INFO - logging in using static token
2024-11-14 14:23:20,243 - INFO - Shard ID None has connected to Gateway (Session ID: 5e73294c4ceeab4fce6378b0c933bf13).
2024-11-14 14:23:22,274 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 14:23:22,276 - INFO - Console is ready and is listening for commands

2024-11-14 14:23:22,276 - ERROR - Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/workspaces/ovr-bot/src/bot.py", line 61, in on_ready
    buttonss=imports.buttonss()
             ^^^^^^^^^^^^^^^^^^
  File "/workspaces/ovr-bot/src/imports.py", line 4, in buttonss
    return buttons.rental_close(), buttons.ticket_close(), buttons.ticket_general(), buttons.ticket_management()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/ovr-bot/src/static/buttons.py", line 50, in rental_close
    import bot
  File "/workspaces/ovr-bot/src/bot.py", line 286, in <module>
    bot.run(os.getenv("TOKEN"), reconnect=True)
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/discord/client.py", line 869, in run
    asyncio.run(runner())
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/runners.py", line 190, in run
    raise RuntimeError(
RuntimeError: asyncio.run() cannot be called from a running event loop
2024-11-14 14:31:50,972 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 14:31:50,973 - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-11-14 14:31:50,974 - INFO - Console is ready and is listening for commands

2024-11-14 14:31:50,975 - INFO - logging in using static token
2024-11-14 14:31:51,668 - INFO - Shard ID None has connected to Gateway (Session ID: c3470ab5772c4286de59eb95b9d37c18).
2024-11-14 14:31:53,718 - ERROR - Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/workspaces/ovr-bot/src/bot.py", line 61, in on_ready
    buttonss=imports.buttonss()
             ^^^^^^^
NameError: name 'imports' is not defined
2024-11-14 14:32:34,933 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 14:32:34,934 - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-11-14 14:32:34,935 - INFO - Console is ready and is listening for commands

2024-11-14 14:32:34,936 - INFO - logging in using static token
2024-11-14 14:32:35,392 - INFO - Shard ID None has connected to Gateway (Session ID: ba3176532619f8ecf7472233041028d7).
2024-11-14 14:32:37,403 - ERROR - Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/workspaces/ovr-bot/src/bot.py", line 61, in on_ready
    buttonss=imports.buttonss()
             ^^^^^^^
NameError: name 'imports' is not defined
2024-11-14 14:32:45,739 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 14:32:45,740 - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-11-14 14:32:45,742 - INFO - Console is ready and is listening for commands

2024-11-14 14:32:45,742 - INFO - logging in using static token
2024-11-14 14:32:46,360 - INFO - Shard ID None has connected to Gateway (Session ID: 165641d6025fcefa4fd79922bd0d3d14).
2024-11-14 14:32:48,372 - ERROR - Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/workspaces/ovr-bot/src/bot.py", line 69, in on_ready
    bot.add_view(buttons.ticket_close_())
                 ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'static.buttons' has no attribute 'ticket_close_'. Did you mean: 'ticket_close'?
2024-11-14 14:33:01,385 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 14:33:01,385 - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-11-14 14:33:01,387 - INFO - Console is ready and is listening for commands

2024-11-14 14:33:01,387 - INFO - logging in using static token
2024-11-14 14:33:01,865 - INFO - Shard ID None has connected to Gateway (Session ID: 09bef953883589d5d22de3de1b1fb680).
2024-11-14 14:33:03,903 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 14:33:03,906 - INFO - Console is ready and is listening for commands

2024-11-14 14:33:03,906 - ERROR - Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/workspaces/ovr-bot/src/bot.py", line 69, in on_ready
    bot.add_view(buttons.ticket_close())
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/ovr-bot/src/static/buttons.py", line 66, in ticket_close
    import bot
  File "/workspaces/ovr-bot/src/bot.py", line 286, in <module>
    bot.run(os.getenv("TOKEN"), reconnect=True)
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/discord/client.py", line 869, in run
    asyncio.run(runner())
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/runners.py", line 190, in run
    raise RuntimeError(
RuntimeError: asyncio.run() cannot be called from a running event loop
2024-11-14 14:36:36,842 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 14:36:36,842 - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-11-14 14:36:36,844 - INFO - Console is ready and is listening for commands

2024-11-14 14:36:36,844 - INFO - logging in using static token
2024-11-14 14:36:37,238 - INFO - Shard ID None has connected to Gateway (Session ID: facb20dddd5f6cc9b223e87cabade055).
2024-11-14 14:36:39,247 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 14:36:39,249 - INFO - Console is ready and is listening for commands

2024-11-14 14:36:39,249 - ERROR - Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/workspaces/ovr-bot/src/bot.py", line 69, in on_ready
    bot.add_view(buttons.ticket_close())
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/ovr-bot/src/static/buttons.py", line 66, in ticket_close
    from bot import transcript
  File "/workspaces/ovr-bot/src/bot.py", line 286, in <module>
    bot.run(os.getenv("TOKEN"), reconnect=True)
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/discord/client.py", line 869, in run
    asyncio.run(runner())
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/runners.py", line 190, in run
    raise RuntimeError(
RuntimeError: asyncio.run() cannot be called from a running event loop
2024-11-14 14:43:45,212 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 14:43:45,213 - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-11-14 14:43:45,215 - INFO - Console is ready and is listening for commands

2024-11-14 14:43:45,216 - INFO - logging in using static token
2024-11-14 14:43:45,838 - INFO - Shard ID None has connected to Gateway (Session ID: 0ec37587aafaece90d43155b1273ef81).
2024-11-14 14:43:47,848 - ERROR - Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/workspaces/ovr-bot/src/bot.py", line 64, in on_ready
    v.add_item(buttons.ticket_general())
               ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'static.buttons' has no attribute 'ticket_general' (most likely due to a circular import)
2024-11-14 14:47:35,086 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 14:47:35,088 - INFO - Console is ready and is listening for commands

2024-11-14 14:47:35,088 - INFO - logging in using static token
2024-11-14 14:47:35,511 - INFO - Shard ID None has connected to Gateway (Session ID: 553a98996a4c3c28c4f0dcad5c0cb60c).
2024-11-14 14:47:37,922 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 14:47:37,922 - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-11-14 14:47:37,924 - INFO - Console is ready and is listening for commands

2024-11-14 14:47:37,924 - INFO - logging in using static token
2024-11-14 14:47:38,442 - INFO - Shard ID None has connected to Gateway (Session ID: 2c26e82a848c5c89b5126b155249a0f7).
2024-11-14 14:47:40,446 - ERROR - Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/workspaces/ovr-bot/src/bot.py", line 64, in on_ready
    v.add_item(buttons.ticket_general())
               ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: partially initialized module 'static.buttons' has no attribute 'ticket_general' (most likely due to a circular import)
2024-11-14 14:57:18,812 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 14:57:18,814 - INFO - Console is ready and is listening for commands

2024-11-14 14:57:18,815 - INFO - logging in using static token
2024-11-14 14:57:19,550 - INFO - Shard ID None has connected to Gateway (Session ID: 96d57fe580ee3158670f17b6cb3fed25).
2024-11-14 14:58:14,160 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 14:58:14,160 - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-11-14 14:58:14,162 - INFO - Console is ready and is listening for commands

2024-11-14 14:58:14,162 - INFO - logging in using static token
2024-11-14 14:58:14,963 - INFO - Shard ID None has connected to Gateway (Session ID: 48b38126ec8fb2034537a4f827c07294).
2024-11-14 14:58:16,968 - ERROR - Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/workspaces/ovr-bot/src/bot.py", line 171, in on_ready
    buttonss=imports.buttonss()
             ^^^^^^^
NameError: name 'imports' is not defined
2024-11-14 15:02:24,100 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 15:02:24,101 - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-11-14 15:02:24,103 - INFO - Console is ready and is listening for commands

2024-11-14 15:02:24,103 - INFO - logging in using static token
2024-11-14 15:02:24,642 - INFO - Shard ID None has connected to Gateway (Session ID: e0380e27423297c9eefb8fac694f6d49).
2024-11-14 15:02:26,653 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 15:02:26,655 - INFO - Console is ready and is listening for commands

2024-11-14 15:02:26,655 - ERROR - Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/discord/client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "/workspaces/ovr-bot/src/bot.py", line 174, in on_ready
    bot.add_view(ticket_close())
                 ^^^^^^^^^^^^^^
  File "/workspaces/ovr-bot/src/bot.py", line 99, in ticket_close
    from bot import transcript
  File "/workspaces/ovr-bot/src/bot.py", line 391, in <module>
    bot.run(os.getenv("TOKEN"), reconnect=True)
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/discord/client.py", line 869, in run
    asyncio.run(runner())
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/runners.py", line 190, in run
    raise RuntimeError(
RuntimeError: asyncio.run() cannot be called from a running event loop
2024-11-14 15:17:34,611 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 15:17:34,612 - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-11-14 15:17:34,613 - INFO - Console is ready and is listening for commands

2024-11-14 15:17:34,614 - INFO - logging in using static token
2024-11-14 15:17:35,191 - INFO - Shard ID None has connected to Gateway (Session ID: 71646115e1c38818aa1fa752de13966b).
2024-11-14 15:17:37,198 - INFO - Bot ready.
2024-11-14 15:17:45,623 - ERROR - Ignoring exception in command 'openrental'
Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/discord/app_commands/commands.py", line 858, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/ovr-bot/src/bot.py", line 236, in openrental
    await ctx.response.send_message(view=buttons.rental_channel(ctx.guild_id, channel.id), ephemeral=True)
                                         ^^^^^^^
NameError: name 'buttons' is not defined. Did you mean: 'Button'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/discord/app_commands/tree.py", line 1310, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/discord/app_commands/commands.py", line 883, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/discord/app_commands/commands.py", line 876, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'openrental' raised an exception: NameError: name 'buttons' is not defined
2024-11-14 15:18:26,036 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 15:18:26,037 - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-11-14 15:18:26,038 - INFO - Console is ready and is listening for commands

2024-11-14 15:18:26,039 - INFO - logging in using static token
2024-11-14 15:18:26,478 - INFO - Shard ID None has connected to Gateway (Session ID: 1241a49d51bc69cf26e8991b16895168).
2024-11-14 15:18:28,484 - INFO - Bot ready.
2024-11-14 15:18:33,492 - INFO - NEW OBJECT ON global_variables/openedRentals.json: DATA {1306639417376641065: {'renter_id': 787065576995553301, 'is_active': None, 'employee_id': None, 'guild_id': 1274894955663593492}}
2024-11-14 15:18:33,493 - ERROR - Ignoring exception in command 'openrental'
Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/discord/app_commands/commands.py", line 858, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/ovr-bot/src/bot.py", line 238, in openrental
    await channel.send(content='@her', embed=embeds.rental_channel(ctx.user, contact_info, people_in_house, renting_time, house_type.name, pets_in_house.name), view=buttons.rental_close())
                                                                                                                                                                     ^^^^^^^
NameError: name 'buttons' is not defined. Did you mean: 'Button'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/discord/app_commands/tree.py", line 1310, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/discord/app_commands/commands.py", line 883, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/discord/app_commands/commands.py", line 876, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'openrental' raised an exception: NameError: name 'buttons' is not defined
2024-11-14 15:19:19,349 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 15:19:19,350 - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-11-14 15:19:19,351 - INFO - Console is ready and is listening for commands

2024-11-14 15:19:19,352 - INFO - logging in using static token
2024-11-14 15:19:19,777 - INFO - Shard ID None has connected to Gateway (Session ID: 6ca4e74165cbe1eff4c2aa1dafc42422).
2024-11-14 15:19:21,785 - INFO - Bot ready.
2024-11-14 15:19:28,692 - INFO - NEW OBJECT ON global_variables/openedRentals.json: DATA {1306639647883006044: {'renter_id': 787065576995553301, 'is_active': None, 'employee_id': None, 'guild_id': 1274894955663593492}}
2024-11-14 15:19:44,358 - INFO - OBJECT DELETED ON global_variables/openedRentals.json: KEY 1306639647883006044; DATA: {'renter_id': 787065576995553301, 'is_active': None, 'employee_id': None, 'guild_id': 1274894955663593492}
2024-11-14 15:21:23,941 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 15:21:23,942 - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-11-14 15:21:23,945 - INFO - Console is ready and is listening for commands

2024-11-14 15:21:23,946 - INFO - logging in using static token
2024-11-14 15:21:24,532 - INFO - Shard ID None has connected to Gateway (Session ID: 874c0b85e2c194a9630d8c7b6a1c035b).
2024-11-14 15:21:26,551 - INFO - Bot ready.
2024-11-14 15:22:30,298 - INFO - NEW OBJECT ON global_variables/openedRentals.json: DATA {1306640410864648303: {'renter_id': 787065576995553301, 'is_active': None, 'employee_id': None, 'guild_id': 1274894955663593492}}
2024-11-14 15:22:33,686 - INFO - OBJECT DELETED ON global_variables/openedRentals.json: KEY 1306640410864648303; DATA: {'renter_id': 787065576995553301, 'is_active': None, 'employee_id': None, 'guild_id': 1274894955663593492}
2024-11-14 15:23:01,501 - INFO - 

NEW SESSION --------------------------------------------------------------------------------------------
2024-11-14 15:23:01,502 - WARNING - PyNaCl is not installed, voice will NOT be supported
2024-11-14 15:23:01,503 - INFO - Console is ready and is listening for commands

2024-11-14 15:23:01,504 - INFO - logging in using static token
2024-11-14 15:23:02,066 - INFO - Shard ID None has connected to Gateway (Session ID: 825c7375785cf1fc12e7f101572d5a8c).
2024-11-14 15:23:04,072 - INFO - Bot ready.
2024-11-14 15:23:08,687 - INFO - NEW OBJECT ON global_variables/openedTickets.json: DATA {'1306640570893991980': {'creator_id': 787065576995553301, 'employee_id': None, 'type': 'gen'}}
2024-11-14 15:23:12,860 - INFO - OBJECT DELETED ON global_variables/openedTickets.json: KEY 1306640570893991980; DATA: {'creator_id': 787065576995553301, 'employee_id': None, 'type': 'gen'}
2024-11-14 15:23:28,453 - INFO - NEW OBJECT ON global_variables/openedTickets.json: DATA {'1306640654067171369': {'creator_id': 787065576995553301, 'employee_id': None, 'type': 'mana'}}
2024-11-14 15:23:32,724 - INFO - OBJECT DELETED ON global_variables/openedTickets.json: KEY 1306640654067171369; DATA: {'creator_id': 787065576995553301, 'employee_id': None, 'type': 'mana'}
